-- Recalcula a matriz de status das agendas com a sequência correta:
-- CADASTRO -> MEDIDA -> ORCAMENTO -> APRESENTACAO -> FECHAMENTO -> MEDIDA_FINA -> PROJETO_TECNICO -> PRODUCAO
-- Serviço de corte permanece como fluxo terminal direto de fábrica.

UPDATE agenda_loja
SET
  fluxo_tipo = CASE
    WHEN origem_fluxo IN ('PLANO_CORTE', 'VENDA_PLANO_CORTE') THEN 'SERVICO_CORTE'
    ELSE 'MARCENARIA'
  END,
  subetapa = CASE
    WHEN origem_fluxo IN ('PLANO_CORTE', 'VENDA_PLANO_CORTE') THEN 'SERVICO_CORTE_FITA_BORDA'
    WHEN UPPER(COALESCE(categoria, '')) IN ('CADASTRO') THEN 'CADASTRO'
    WHEN UPPER(COALESCE(categoria, '')) IN ('MEDIDA', 'MEDIDA_AGENDADA', 'AGENDAR_MEDIDA', 'AGENDAR_MEDIDA_VENDA') THEN 'MEDIDA'
    WHEN UPPER(COALESCE(categoria, '')) IN ('ORCAMENTO', 'CRIAR_ORCAMENTO', 'AGENDAR_ORCAMENTO') THEN 'ORCAMENTO'
    WHEN UPPER(COALESCE(categoria, '')) IN ('APRESENTACAO', 'AGENDAR_APRESENTACAO') THEN 'APRESENTACAO'
    WHEN UPPER(COALESCE(categoria, '')) IN ('CONTRATO', 'CONTRATO_GERADO', 'VENDA_FECHADA', 'CONTRATO_ASSINADO') THEN 'FECHAMENTO'
    WHEN UPPER(COALESCE(categoria, '')) IN ('AGENDAR_MEDIDA_FINA', 'MEDIDA_FINA') THEN 'MEDIDA_FINA'
    WHEN UPPER(COALESCE(categoria, '')) IN ('AGUARDANDO_PROJETO_TECNICO', 'PROJETO_TECNICO_EM_ANDAMENTO', 'PROJETO_TECNICO_CONCLUIDO', 'PROJETO_TECNICO_APROVADO') THEN 'PROJETO_TECNICO'
    WHEN UPPER(COALESCE(categoria, '')) IN ('PRODUCAO_RECEBIDA', 'PRODUCAO_EM_ANDAMENTO', 'PRODUCAO_FINALIZADA', 'PREPARACAO_TECNICA', 'CORTE', 'MONTAGEM_INTERNA', 'ACABAMENTO', 'CONFERENCIA_QUALIDADE') THEN 'PRODUCAO'
    WHEN UPPER(COALESCE(categoria, '')) IN ('AGENDAR_ENTREGA', 'ENTREGA_AGENDADA', 'EM_ENTREGA', 'ENTREGA_FINALIZADA') THEN 'ENTREGA'
    WHEN UPPER(COALESCE(categoria, '')) IN ('AGENDAR_MONTAGEM', 'MONTAGEM_AGENDADA', 'MONTAGEM_CLIENTE_AGENDADA', 'EM_MONTAGEM', 'EM_MONTAGEM_CLIENTE', 'MONTAGEM_FINALIZADA', 'MONTAGEM_CLIENTE_FINALIZADA') THEN 'MONTAGEM'
    WHEN UPPER(COALESCE(categoria, '')) = 'GARANTIA' THEN 'GARANTIA'
    WHEN UPPER(COALESCE(categoria, '')) = 'ASSISTENCIA' THEN 'ASSISTENCIA'
    WHEN UPPER(COALESCE(categoria, '')) IN ('MANUTENCAO', 'AGENDAR_POS_VENDA') THEN 'MANUTENCAO'
    ELSE 'CADASTRO'
  END,
  macroetapa = CASE
    WHEN origem_fluxo IN ('PLANO_CORTE', 'VENDA_PLANO_CORTE') THEN 'FABRICA'
    WHEN UPPER(COALESCE(categoria, '')) IN ('CADASTRO', 'MEDIDA', 'MEDIDA_AGENDADA', 'AGENDAR_MEDIDA', 'AGENDAR_MEDIDA_VENDA', 'ORCAMENTO', 'CRIAR_ORCAMENTO', 'AGENDAR_ORCAMENTO', 'APRESENTACAO', 'AGENDAR_APRESENTACAO', 'CONTRATO', 'CONTRATO_GERADO', 'VENDA_FECHADA', 'CONTRATO_ASSINADO') THEN 'COMERCIAL'
    WHEN UPPER(COALESCE(categoria, '')) IN ('AGENDAR_MEDIDA_FINA', 'MEDIDA_FINA', 'AGUARDANDO_PROJETO_TECNICO', 'PROJETO_TECNICO_EM_ANDAMENTO', 'PROJETO_TECNICO_CONCLUIDO', 'PROJETO_TECNICO_APROVADO') THEN 'ENGENHARIA'
    WHEN UPPER(COALESCE(categoria, '')) IN ('PRODUCAO_RECEBIDA', 'PRODUCAO_EM_ANDAMENTO', 'PRODUCAO_FINALIZADA', 'PREPARACAO_TECNICA', 'CORTE', 'MONTAGEM_INTERNA', 'ACABAMENTO', 'CONFERENCIA_QUALIDADE') THEN 'FABRICA'
    WHEN UPPER(COALESCE(categoria, '')) IN ('AGENDAR_ENTREGA', 'ENTREGA_AGENDADA', 'EM_ENTREGA', 'ENTREGA_FINALIZADA', 'AGENDAR_MONTAGEM', 'MONTAGEM_AGENDADA', 'MONTAGEM_CLIENTE_AGENDADA', 'EM_MONTAGEM', 'EM_MONTAGEM_CLIENTE', 'MONTAGEM_FINALIZADA', 'MONTAGEM_CLIENTE_FINALIZADA') THEN 'LOGISTICA'
    WHEN UPPER(COALESCE(categoria, '')) IN ('GARANTIA', 'ASSISTENCIA', 'MANUTENCAO', 'AGENDAR_POS_VENDA') THEN 'POS_VENDA'
    ELSE 'COMERCIAL'
  END;

UPDATE agenda_fabrica
SET
  fluxo_tipo = CASE
    WHEN plano_corte_id IS NOT NULL OR origem_fluxo IN ('PLANO_CORTE', 'VENDA_PLANO_CORTE') THEN 'SERVICO_CORTE'
    ELSE 'MARCENARIA'
  END,
  subetapa = CASE
    WHEN plano_corte_id IS NOT NULL OR origem_fluxo IN ('PLANO_CORTE', 'VENDA_PLANO_CORTE') THEN 'SERVICO_CORTE_FITA_BORDA'
    WHEN UPPER(COALESCE(categoria, '')) IN ('CADASTRO') THEN 'CADASTRO'
    WHEN UPPER(COALESCE(categoria, '')) IN ('MEDIDA', 'MEDIDA_AGENDADA', 'AGENDAR_MEDIDA', 'AGENDAR_MEDIDA_VENDA') THEN 'MEDIDA'
    WHEN UPPER(COALESCE(categoria, '')) IN ('ORCAMENTO', 'CRIAR_ORCAMENTO', 'AGENDAR_ORCAMENTO') THEN 'ORCAMENTO'
    WHEN UPPER(COALESCE(categoria, '')) IN ('APRESENTACAO', 'AGENDAR_APRESENTACAO') THEN 'APRESENTACAO'
    WHEN UPPER(COALESCE(categoria, '')) IN ('CONTRATO', 'CONTRATO_GERADO', 'VENDA_FECHADA', 'CONTRATO_ASSINADO') THEN 'FECHAMENTO'
    WHEN UPPER(COALESCE(categoria, '')) IN ('AGENDAR_MEDIDA_FINA', 'MEDIDA_FINA') THEN 'MEDIDA_FINA'
    WHEN UPPER(COALESCE(categoria, '')) IN ('AGUARDANDO_PROJETO_TECNICO', 'PROJETO_TECNICO_EM_ANDAMENTO', 'PROJETO_TECNICO_CONCLUIDO', 'PROJETO_TECNICO_APROVADO') THEN 'PROJETO_TECNICO'
    WHEN UPPER(COALESCE(categoria, '')) IN ('PRODUCAO_RECEBIDA', 'PRODUCAO_EM_ANDAMENTO', 'PRODUCAO_FINALIZADA', 'PREPARACAO_TECNICA', 'CORTE', 'MONTAGEM_INTERNA', 'ACABAMENTO', 'CONFERENCIA_QUALIDADE') THEN 'PRODUCAO'
    WHEN UPPER(COALESCE(categoria, '')) IN ('AGENDAR_ENTREGA', 'ENTREGA_AGENDADA', 'EM_ENTREGA', 'ENTREGA_FINALIZADA') THEN 'ENTREGA'
    WHEN UPPER(COALESCE(categoria, '')) IN ('AGENDAR_MONTAGEM', 'MONTAGEM_AGENDADA', 'MONTAGEM_CLIENTE_AGENDADA', 'EM_MONTAGEM', 'EM_MONTAGEM_CLIENTE', 'MONTAGEM_FINALIZADA', 'MONTAGEM_CLIENTE_FINALIZADA') THEN 'MONTAGEM'
    WHEN UPPER(COALESCE(categoria, '')) = 'GARANTIA' THEN 'GARANTIA'
    WHEN UPPER(COALESCE(categoria, '')) = 'ASSISTENCIA' THEN 'ASSISTENCIA'
    WHEN UPPER(COALESCE(categoria, '')) IN ('MANUTENCAO', 'AGENDAR_POS_VENDA') THEN 'MANUTENCAO'
    ELSE CASE
      WHEN origem_fluxo = 'TAREFA' THEN 'PRODUCAO'
      ELSE 'CADASTRO'
    END
  END,
  macroetapa = CASE
    WHEN plano_corte_id IS NOT NULL OR origem_fluxo IN ('PLANO_CORTE', 'VENDA_PLANO_CORTE') THEN 'FABRICA'
    WHEN UPPER(COALESCE(categoria, '')) IN ('CADASTRO', 'MEDIDA', 'MEDIDA_AGENDADA', 'AGENDAR_MEDIDA', 'AGENDAR_MEDIDA_VENDA', 'ORCAMENTO', 'CRIAR_ORCAMENTO', 'AGENDAR_ORCAMENTO', 'APRESENTACAO', 'AGENDAR_APRESENTACAO', 'CONTRATO', 'CONTRATO_GERADO', 'VENDA_FECHADA', 'CONTRATO_ASSINADO') THEN 'COMERCIAL'
    WHEN UPPER(COALESCE(categoria, '')) IN ('AGENDAR_MEDIDA_FINA', 'MEDIDA_FINA', 'AGUARDANDO_PROJETO_TECNICO', 'PROJETO_TECNICO_EM_ANDAMENTO', 'PROJETO_TECNICO_CONCLUIDO', 'PROJETO_TECNICO_APROVADO') THEN 'ENGENHARIA'
    WHEN UPPER(COALESCE(categoria, '')) IN ('PRODUCAO_RECEBIDA', 'PRODUCAO_EM_ANDAMENTO', 'PRODUCAO_FINALIZADA', 'PREPARACAO_TECNICA', 'CORTE', 'MONTAGEM_INTERNA', 'ACABAMENTO', 'CONFERENCIA_QUALIDADE') THEN 'FABRICA'
    WHEN UPPER(COALESCE(categoria, '')) IN ('AGENDAR_ENTREGA', 'ENTREGA_AGENDADA', 'EM_ENTREGA', 'ENTREGA_FINALIZADA', 'AGENDAR_MONTAGEM', 'MONTAGEM_AGENDADA', 'MONTAGEM_CLIENTE_AGENDADA', 'EM_MONTAGEM', 'EM_MONTAGEM_CLIENTE', 'MONTAGEM_FINALIZADA', 'MONTAGEM_CLIENTE_FINALIZADA') THEN 'LOGISTICA'
    WHEN UPPER(COALESCE(categoria, '')) IN ('GARANTIA', 'ASSISTENCIA', 'MANUTENCAO', 'AGENDAR_POS_VENDA') THEN 'POS_VENDA'
    ELSE CASE
      WHEN origem_fluxo = 'TAREFA' THEN 'FABRICA'
      ELSE 'COMERCIAL'
    END
  END;
