export const VENDA_FECHAMENTO_REGRAS = {
  DESCONTO_MAXIMO_PERCENTUAL: 10,
  DESCONTO_PERCENTUAL_STEP: 0.5,
  LIMITE_DESCONTO_RESTRINGIR_PAGAMENTO_PERCENTUAL: 7,
  FORMAS_REMOVIDAS_FECHAMENTO: ['CHEQUE', 'BOLETO'],
  FORMAS_PERMITIDAS_ACIMA_LIMITE_DESCONTO: ['PIX', 'TRANSFERENCIA', 'DINHEIRO'],
  PARCELAS_OPCOES: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
  PARCELAS_MAX_POR_FORMA: {
    PIX: 3,
    TRANSFERENCIA: 1,
    DINHEIRO: 1,
    DEBITO: 1,
  },
} as const;
