ALTER TABLE `agenda_loja`
  ADD COLUMN `fluxo_tipo` VARCHAR(191) NULL,
  ADD COLUMN `macroetapa` VARCHAR(191) NULL,
  ADD COLUMN `subetapa` VARCHAR(191) NULL,
  ADD COLUMN `execucao_etapa` VARCHAR(191) NULL;

ALTER TABLE `agenda_fabrica`
  ADD COLUMN `fluxo_tipo` VARCHAR(191) NULL,
  ADD COLUMN `macroetapa` VARCHAR(191) NULL,
  ADD COLUMN `subetapa` VARCHAR(191) NULL,
  ADD COLUMN `execucao_etapa` VARCHAR(191) NULL;

CREATE INDEX `agenda_loja_fluxo_tipo_idx` ON `agenda_loja`(`fluxo_tipo`);
CREATE INDEX `agenda_loja_macroetapa_idx` ON `agenda_loja`(`macroetapa`);
CREATE INDEX `agenda_loja_subetapa_idx` ON `agenda_loja`(`subetapa`);
CREATE INDEX `agenda_loja_execucao_etapa_idx` ON `agenda_loja`(`execucao_etapa`);

CREATE INDEX `agenda_fabrica_fluxo_tipo_idx` ON `agenda_fabrica`(`fluxo_tipo`);
CREATE INDEX `agenda_fabrica_macroetapa_idx` ON `agenda_fabrica`(`macroetapa`);
CREATE INDEX `agenda_fabrica_subetapa_idx` ON `agenda_fabrica`(`subetapa`);
CREATE INDEX `agenda_fabrica_execucao_etapa_idx` ON `agenda_fabrica`(`execucao_etapa`);

UPDATE `agenda_loja`
SET
  `fluxo_tipo` = 'MARCENARIA',
  `macroetapa` = CASE
    WHEN UPPER(COALESCE(`categoria`, '')) IN ('MEDIDA', 'MEDIDA_AGENDADA', 'AGENDAR_MEDIDA', 'ORCAMENTO', 'CRIAR_ORCAMENTO', 'AGENDAR_ORCAMENTO', 'APRESENTACAO', 'AGENDAR_APRESENTACAO') THEN 'COMERCIAL'
    WHEN UPPER(COALESCE(`categoria`, '')) IN ('CONTRATO', 'CONTRATO_GERADO', 'VENDA_FECHADA', 'CONTRATO_ASSINADO') THEN 'COMERCIAL'
    WHEN UPPER(COALESCE(`categoria`, '')) = 'GARANTIA' THEN 'POS_VENDA'
    WHEN UPPER(COALESCE(`categoria`, '')) = 'ASSISTENCIA' THEN 'POS_VENDA'
    WHEN UPPER(COALESCE(`categoria`, '')) IN ('MANUTENCAO', 'AGENDAR_POS_VENDA') THEN 'POS_VENDA'
    ELSE 'FABRICA'
  END,
  `subetapa` = CASE
    WHEN UPPER(COALESCE(`categoria`, '')) IN ('MEDIDA', 'MEDIDA_AGENDADA', 'AGENDAR_MEDIDA', 'ORCAMENTO', 'CRIAR_ORCAMENTO', 'AGENDAR_ORCAMENTO', 'APRESENTACAO', 'AGENDAR_APRESENTACAO') THEN 'ORCAMENTO'
    WHEN UPPER(COALESCE(`categoria`, '')) IN ('CONTRATO', 'CONTRATO_GERADO', 'VENDA_FECHADA', 'CONTRATO_ASSINADO') THEN 'FECHAMENTO'
    WHEN UPPER(COALESCE(`categoria`, '')) = 'GARANTIA' THEN 'GARANTIA'
    WHEN UPPER(COALESCE(`categoria`, '')) = 'ASSISTENCIA' THEN 'ASSISTENCIA'
    WHEN UPPER(COALESCE(`categoria`, '')) IN ('MANUTENCAO', 'AGENDAR_POS_VENDA') THEN 'MANUTENCAO'
    ELSE 'PRODUCAO'
  END,
  `execucao_etapa` = CASE
    WHEN UPPER(COALESCE(`status`, '')) = 'CONCLUIDO' THEN 'CONCLUIDO'
    WHEN UPPER(COALESCE(`status`, '')) = 'EM_PRODUCAO' THEN 'EM_ANDAMENTO'
    WHEN UPPER(COALESCE(`status`, '')) = 'PAUSADO' THEN 'EM_ANDAMENTO'
    WHEN UPPER(COALESCE(`status`, '')) = 'EM_ANDAMENTO' AND UPPER(COALESCE(`categoria`, '')) IN ('AGENDAR_MEDIDA', 'AGENDAR_APRESENTACAO', 'AGENDAR_MEDIDA_FINA', 'MEDIDA_FINA', 'AGUARDANDO_PROJETO_TECNICO', 'MONTAGEM_CLIENTE_AGENDADA', 'AGENDAR_POS_VENDA', 'AGENDAR_ENTREGA', 'ENTREGA_AGENDADA', 'AGENDAR_MONTAGEM', 'MONTAGEM_AGENDADA') THEN 'AGENDADO'
    WHEN UPPER(COALESCE(`status`, '')) = 'EM_ANDAMENTO' THEN 'EM_ANDAMENTO'
    WHEN UPPER(COALESCE(`status`, '')) = 'PENDENTE' THEN 'PENDENTE'
    ELSE 'PENDENTE'
  END;

UPDATE `agenda_fabrica`
SET
  `fluxo_tipo` = CASE
    WHEN `plano_corte_id` IS NOT NULL THEN 'SERVICO_CORTE'
    WHEN UPPER(COALESCE(`origem_fluxo`, '')) IN ('PLANO_CORTE', 'VENDA_PLANO_CORTE') THEN 'SERVICO_CORTE'
    ELSE 'MARCENARIA'
  END,
  `macroetapa` = CASE
    WHEN `plano_corte_id` IS NOT NULL THEN 'FABRICA'
    WHEN UPPER(COALESCE(`categoria`, '')) IN ('AGENDAR_MEDIDA_FINA', 'MEDIDA_FINA') THEN 'ENGENHARIA'
    WHEN UPPER(COALESCE(`categoria`, '')) IN ('AGUARDANDO_PROJETO_TECNICO', 'PROJETO_TECNICO_EM_ANDAMENTO', 'PROJETO_TECNICO_CONCLUIDO', 'PROJETO_TECNICO_APROVADO') THEN 'ENGENHARIA'
    WHEN UPPER(COALESCE(`categoria`, '')) IN ('PRODUCAO_RECEBIDA', 'PRODUCAO_EM_ANDAMENTO', 'PRODUCAO_FINALIZADA', 'PREPARACAO_TECNICA', 'CORTE', 'MONTAGEM_INTERNA', 'ACABAMENTO', 'CONFERENCIA_QUALIDADE') THEN 'FABRICA'
    WHEN UPPER(COALESCE(`categoria`, '')) IN ('AGENDAR_ENTREGA', 'ENTREGA_AGENDADA', 'EM_ENTREGA', 'ENTREGA_FINALIZADA') THEN 'LOGISTICA'
    WHEN UPPER(COALESCE(`categoria`, '')) IN ('AGENDAR_MONTAGEM', 'MONTAGEM_AGENDADA', 'MONTAGEM_CLIENTE_AGENDADA', 'EM_MONTAGEM', 'EM_MONTAGEM_CLIENTE', 'MONTAGEM_FINALIZADA', 'MONTAGEM_CLIENTE_FINALIZADA') THEN 'LOGISTICA'
    WHEN UPPER(COALESCE(`categoria`, '')) = 'GARANTIA' THEN 'POS_VENDA'
    WHEN UPPER(COALESCE(`categoria`, '')) = 'ASSISTENCIA' THEN 'POS_VENDA'
    WHEN UPPER(COALESCE(`categoria`, '')) IN ('MANUTENCAO', 'AGENDAR_POS_VENDA') THEN 'POS_VENDA'
    ELSE 'FABRICA'
  END,
  `subetapa` = CASE
    WHEN `plano_corte_id` IS NOT NULL THEN 'SERVICO_CORTE_FITA_BORDA'
    WHEN UPPER(COALESCE(`categoria`, '')) IN ('AGENDAR_MEDIDA_FINA', 'MEDIDA_FINA') THEN 'MEDIDA_FINA'
    WHEN UPPER(COALESCE(`categoria`, '')) IN ('AGUARDANDO_PROJETO_TECNICO', 'PROJETO_TECNICO_EM_ANDAMENTO', 'PROJETO_TECNICO_CONCLUIDO', 'PROJETO_TECNICO_APROVADO') THEN 'PROJETO_TECNICO'
    WHEN UPPER(COALESCE(`categoria`, '')) IN ('PRODUCAO_RECEBIDA', 'PRODUCAO_EM_ANDAMENTO', 'PRODUCAO_FINALIZADA', 'PREPARACAO_TECNICA', 'CORTE', 'MONTAGEM_INTERNA', 'ACABAMENTO', 'CONFERENCIA_QUALIDADE') THEN 'PRODUCAO'
    WHEN UPPER(COALESCE(`categoria`, '')) IN ('AGENDAR_ENTREGA', 'ENTREGA_AGENDADA', 'EM_ENTREGA', 'ENTREGA_FINALIZADA') THEN 'ENTREGA'
    WHEN UPPER(COALESCE(`categoria`, '')) IN ('AGENDAR_MONTAGEM', 'MONTAGEM_AGENDADA', 'MONTAGEM_CLIENTE_AGENDADA', 'EM_MONTAGEM', 'EM_MONTAGEM_CLIENTE', 'MONTAGEM_FINALIZADA', 'MONTAGEM_CLIENTE_FINALIZADA') THEN 'MONTAGEM'
    WHEN UPPER(COALESCE(`categoria`, '')) = 'GARANTIA' THEN 'GARANTIA'
    WHEN UPPER(COALESCE(`categoria`, '')) = 'ASSISTENCIA' THEN 'ASSISTENCIA'
    WHEN UPPER(COALESCE(`categoria`, '')) IN ('MANUTENCAO', 'AGENDAR_POS_VENDA') THEN 'MANUTENCAO'
    ELSE 'PRODUCAO'
  END,
  `execucao_etapa` = CASE
    WHEN UPPER(COALESCE(`status`, '')) = 'CONCLUIDO' THEN 'CONCLUIDO'
    WHEN UPPER(COALESCE(`status`, '')) = 'EM_PRODUCAO' THEN 'EM_ANDAMENTO'
    WHEN UPPER(COALESCE(`status`, '')) = 'PAUSADO' THEN 'EM_ANDAMENTO'
    WHEN UPPER(COALESCE(`status`, '')) = 'EM_ANDAMENTO' AND UPPER(COALESCE(`categoria`, '')) IN ('AGENDAR_MEDIDA', 'AGENDAR_APRESENTACAO', 'AGENDAR_MEDIDA_FINA', 'MEDIDA_FINA', 'AGUARDANDO_PROJETO_TECNICO', 'MONTAGEM_CLIENTE_AGENDADA', 'AGENDAR_POS_VENDA', 'AGENDAR_ENTREGA', 'ENTREGA_AGENDADA', 'AGENDAR_MONTAGEM', 'MONTAGEM_AGENDADA') THEN 'AGENDADO'
    WHEN UPPER(COALESCE(`status`, '')) = 'EM_ANDAMENTO' THEN 'EM_ANDAMENTO'
    WHEN UPPER(COALESCE(`status`, '')) = 'PENDENTE' THEN 'PENDENTE'
    ELSE 'PENDENTE'
  END;