-- CreateTable
CREATE TABLE `funcionarios` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `nome` VARCHAR(191) NOT NULL,
    `cpf` VARCHAR(191) NOT NULL,
    `rg` VARCHAR(191) NULL,
    `telefone` VARCHAR(191) NULL,
    `whatsapp` VARCHAR(191) NULL,
    `email` VARCHAR(191) NULL,
    `estado_civil` VARCHAR(191) NULL,
    `escolaridade` VARCHAR(191) NULL,
    `cep` VARCHAR(191) NULL,
    `endereco` VARCHAR(191) NULL,
    `numero` VARCHAR(191) NULL,
    `bairro` VARCHAR(191) NULL,
    `cidade` VARCHAR(191) NULL,
    `estado` VARCHAR(191) NULL,
    `registro` VARCHAR(191) NULL,
    `admissao` DATETIME(3) NULL,
    `demissao` DATETIME(3) NULL,
    `salario_base` DECIMAL(12, 2) NULL,
    `salario_adicional` DECIMAL(12, 2) NULL,
    `custo_hora` DECIMAL(12, 2) NULL,
    `horario_entrada` VARCHAR(191) NULL,
    `horario_almoco` VARCHAR(191) NULL,
    `horario_saida` VARCHAR(191) NULL,
    `conta_bancaria` VARCHAR(191) NULL,
    `forma_pagamento` VARCHAR(191) NULL,
    `data_pagamento` DATETIME(3) NULL,
    `criado_em` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `atualizado_em` DATETIME(3) NOT NULL,

    UNIQUE INDEX `funcionarios_cpf_key`(`cpf`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
