/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/agendamentos/': RouteRecordInfo<
      '/agendamentos/',
      '/agendamentos',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/alterar-senha': RouteRecordInfo<
      '/alterar-senha',
      '/alterar-senha',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/arquivos/[id]': RouteRecordInfo<
      '/arquivos/[id]',
      '/arquivos/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/arquivos/pdf/[id]': RouteRecordInfo<
      '/arquivos/pdf/[id]',
      '/arquivos/pdf/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/clientes/': RouteRecordInfo<
      '/clientes/',
      '/clientes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/clientes/[id]': RouteRecordInfo<
      '/clientes/[id]',
      '/clientes/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/comercial/': RouteRecordInfo<
      '/comercial/',
      '/comercial',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/compras/': RouteRecordInfo<
      '/compras/',
      '/compras',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/compras/[id]': RouteRecordInfo<
      '/compras/[id]',
      '/compras/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/configuracoes/configuracoes': RouteRecordInfo<
      '/configuracoes/configuracoes',
      '/configuracoes/configuracoes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/configuracoes/permissoes': RouteRecordInfo<
      '/configuracoes/permissoes',
      '/configuracoes/permissoes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/configuracoes/usuarios': RouteRecordInfo<
      '/configuracoes/usuarios',
      '/configuracoes/usuarios',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/contratos/': RouteRecordInfo<
      '/contratos/',
      '/contratos',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/contratos/[id]': RouteRecordInfo<
      '/contratos/[id]',
      '/contratos/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/contratos/clausulas': RouteRecordInfo<
      '/contratos/clausulas',
      '/contratos/clausulas',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/debug/update': RouteRecordInfo<
      '/debug/update',
      '/debug/update',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/despesas/': RouteRecordInfo<
      '/despesas/',
      '/despesas',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/despesas/[id]': RouteRecordInfo<
      '/despesas/[id]',
      '/despesas/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/financeiro/contas-pagar/': RouteRecordInfo<
      '/financeiro/contas-pagar/',
      '/financeiro/contas-pagar',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/financeiro/contas-receber/': RouteRecordInfo<
      '/financeiro/contas-receber/',
      '/financeiro/contas-receber',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/fornecedor/': RouteRecordInfo<
      '/fornecedor/',
      '/fornecedor',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/fornecedor/[id]': RouteRecordInfo<
      '/fornecedor/[id]',
      '/fornecedor/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/funcionarios/': RouteRecordInfo<
      '/funcionarios/',
      '/funcionarios',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/funcionarios/[id]': RouteRecordInfo<
      '/funcionarios/[id]',
      '/funcionarios/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/orcamentos/': RouteRecordInfo<
      '/orcamentos/',
      '/orcamentos',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/orcamentos/[id]': RouteRecordInfo<
      '/orcamentos/[id]',
      '/orcamentos/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/orcamentos/cliente/[id]': RouteRecordInfo<
      '/orcamentos/cliente/[id]',
      '/orcamentos/cliente/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/orcamentos/lista': RouteRecordInfo<
      '/orcamentos/lista',
      '/orcamentos/lista',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/orcamentos/processo': RouteRecordInfo<
      '/orcamentos/processo',
      '/orcamentos/processo',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/pendente': RouteRecordInfo<
      '/pendente',
      '/pendente',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/plano-corte/': RouteRecordInfo<
      '/plano-corte/',
      '/plano-corte',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/plano-corte/[id]': RouteRecordInfo<
      '/plano-corte/[id]',
      '/plano-corte/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/plano-corte/itens/': RouteRecordInfo<
      '/plano-corte/itens/',
      '/plano-corte/itens',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/plano-corte/itens/[id]': RouteRecordInfo<
      '/plano-corte/itens/[id]',
      '/plano-corte/itens/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/plano-corte/kanban': RouteRecordInfo<
      '/plano-corte/kanban',
      '/plano-corte/kanban',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/plano-corte/venda': RouteRecordInfo<
      '/plano-corte/venda',
      '/plano-corte/venda',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/producao/': RouteRecordInfo<
      '/producao/',
      '/producao',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/produtos/': RouteRecordInfo<
      '/produtos/',
      '/produtos',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/produtos/[id]': RouteRecordInfo<
      '/produtos/[id]',
      '/produtos/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/relatorios/': RouteRecordInfo<
      '/relatorios/',
      '/relatorios',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/relatorios/dashboard-resumo': RouteRecordInfo<
      '/relatorios/dashboard-resumo',
      '/relatorios/dashboard-resumo',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/relatorios/despesas-categoria': RouteRecordInfo<
      '/relatorios/despesas-categoria',
      '/relatorios/despesas-categoria',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/relatorios/status-obras': RouteRecordInfo<
      '/relatorios/status-obras',
      '/relatorios/status-obras',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/rh/ponto/convites': RouteRecordInfo<
      '/rh/ponto/convites',
      '/rh/ponto/convites',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/rh/ponto/fechamento': RouteRecordInfo<
      '/rh/ponto/fechamento',
      '/rh/ponto/fechamento',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/rh/ponto/relatorio/': RouteRecordInfo<
      '/rh/ponto/relatorio/',
      '/rh/ponto/relatorio',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/vendas/': RouteRecordInfo<
      '/vendas/',
      '/vendas',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/vendas/[id]': RouteRecordInfo<
      '/vendas/[id]',
      '/vendas/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/vendas/fechamento': RouteRecordInfo<
      '/vendas/fechamento',
      '/vendas/fechamento',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/vendas/kanban': RouteRecordInfo<
      '/vendas/kanban',
      '/vendas/kanban',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/vendas/nova-venda': RouteRecordInfo<
      '/vendas/nova-venda',
      '/vendas/nova-venda',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/agendamentos/index.vue': {
      routes:
        | '/agendamentos/'
      views:
        | never
    }
    'src/pages/alterar-senha.vue': {
      routes:
        | '/alterar-senha'
      views:
        | never
    }
    'src/pages/arquivos/[id].vue': {
      routes:
        | '/arquivos/[id]'
      views:
        | never
    }
    'src/pages/arquivos/pdf/[id].vue': {
      routes:
        | '/arquivos/pdf/[id]'
      views:
        | never
    }
    'src/pages/clientes/index.vue': {
      routes:
        | '/clientes/'
      views:
        | never
    }
    'src/pages/clientes/[id].vue': {
      routes:
        | '/clientes/[id]'
      views:
        | never
    }
    'src/pages/comercial/index.vue': {
      routes:
        | '/comercial/'
      views:
        | never
    }
    'src/pages/compras/index.vue': {
      routes:
        | '/compras/'
      views:
        | never
    }
    'src/pages/compras/[id].vue': {
      routes:
        | '/compras/[id]'
      views:
        | never
    }
    'src/pages/configuracoes/configuracoes.vue': {
      routes:
        | '/configuracoes/configuracoes'
      views:
        | never
    }
    'src/pages/configuracoes/permissoes.vue': {
      routes:
        | '/configuracoes/permissoes'
      views:
        | never
    }
    'src/pages/configuracoes/usuarios.vue': {
      routes:
        | '/configuracoes/usuarios'
      views:
        | never
    }
    'src/pages/contratos/index.vue': {
      routes:
        | '/contratos/'
      views:
        | never
    }
    'src/pages/contratos/[id].vue': {
      routes:
        | '/contratos/[id]'
      views:
        | never
    }
    'src/pages/contratos/clausulas.vue': {
      routes:
        | '/contratos/clausulas'
      views:
        | never
    }
    'src/pages/debug/update.vue': {
      routes:
        | '/debug/update'
      views:
        | never
    }
    'src/pages/despesas/index.vue': {
      routes:
        | '/despesas/'
      views:
        | never
    }
    'src/pages/despesas/[id].vue': {
      routes:
        | '/despesas/[id]'
      views:
        | never
    }
    'src/pages/financeiro/contas-pagar/index.vue': {
      routes:
        | '/financeiro/contas-pagar/'
      views:
        | never
    }
    'src/pages/financeiro/contas-receber/index.vue': {
      routes:
        | '/financeiro/contas-receber/'
      views:
        | never
    }
    'src/pages/fornecedor/index.vue': {
      routes:
        | '/fornecedor/'
      views:
        | never
    }
    'src/pages/fornecedor/[id].vue': {
      routes:
        | '/fornecedor/[id]'
      views:
        | never
    }
    'src/pages/funcionarios/index.vue': {
      routes:
        | '/funcionarios/'
      views:
        | never
    }
    'src/pages/funcionarios/[id].vue': {
      routes:
        | '/funcionarios/[id]'
      views:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
    }
    'src/pages/orcamentos/index.vue': {
      routes:
        | '/orcamentos/'
      views:
        | never
    }
    'src/pages/orcamentos/[id].vue': {
      routes:
        | '/orcamentos/[id]'
      views:
        | never
    }
    'src/pages/orcamentos/cliente/[id].vue': {
      routes:
        | '/orcamentos/cliente/[id]'
      views:
        | never
    }
    'src/pages/orcamentos/lista.vue': {
      routes:
        | '/orcamentos/lista'
      views:
        | never
    }
    'src/pages/orcamentos/processo.vue': {
      routes:
        | '/orcamentos/processo'
      views:
        | never
    }
    'src/pages/pendente.vue': {
      routes:
        | '/pendente'
      views:
        | never
    }
    'src/pages/plano-corte/index.vue': {
      routes:
        | '/plano-corte/'
      views:
        | never
    }
    'src/pages/plano-corte/[id].vue': {
      routes:
        | '/plano-corte/[id]'
      views:
        | never
    }
    'src/pages/plano-corte/itens/index.vue': {
      routes:
        | '/plano-corte/itens/'
      views:
        | never
    }
    'src/pages/plano-corte/itens/[id].vue': {
      routes:
        | '/plano-corte/itens/[id]'
      views:
        | never
    }
    'src/pages/plano-corte/kanban.vue': {
      routes:
        | '/plano-corte/kanban'
      views:
        | never
    }
    'src/pages/plano-corte/venda.vue': {
      routes:
        | '/plano-corte/venda'
      views:
        | never
    }
    'src/pages/producao/index.vue': {
      routes:
        | '/producao/'
      views:
        | never
    }
    'src/pages/produtos/index.vue': {
      routes:
        | '/produtos/'
      views:
        | never
    }
    'src/pages/produtos/[id].vue': {
      routes:
        | '/produtos/[id]'
      views:
        | never
    }
    'src/pages/relatorios/index.vue': {
      routes:
        | '/relatorios/'
      views:
        | never
    }
    'src/pages/relatorios/dashboard-resumo.vue': {
      routes:
        | '/relatorios/dashboard-resumo'
      views:
        | never
    }
    'src/pages/relatorios/despesas-categoria.vue': {
      routes:
        | '/relatorios/despesas-categoria'
      views:
        | never
    }
    'src/pages/relatorios/status-obras.vue': {
      routes:
        | '/relatorios/status-obras'
      views:
        | never
    }
    'src/pages/rh/ponto/convites.vue': {
      routes:
        | '/rh/ponto/convites'
      views:
        | never
    }
    'src/pages/rh/ponto/fechamento.vue': {
      routes:
        | '/rh/ponto/fechamento'
      views:
        | never
    }
    'src/pages/rh/ponto/relatorio/index.vue': {
      routes:
        | '/rh/ponto/relatorio/'
      views:
        | never
    }
    'src/pages/vendas/index.vue': {
      routes:
        | '/vendas/'
      views:
        | never
    }
    'src/pages/vendas/[id].vue': {
      routes:
        | '/vendas/[id]'
      views:
        | never
    }
    'src/pages/vendas/fechamento.vue': {
      routes:
        | '/vendas/fechamento'
      views:
        | never
    }
    'src/pages/vendas/kanban.vue': {
      routes:
        | '/vendas/kanban'
      views:
        | never
    }
    'src/pages/vendas/nova-venda.vue': {
      routes:
        | '/vendas/nova-venda'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
