/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/clientes/': RouteRecordInfo<
      '/clientes/',
      '/clientes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/clientes/[id]': RouteRecordInfo<
      '/clientes/[id]',
      '/clientes/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/clientes/novo': RouteRecordInfo<
      '/clientes/novo',
      '/clientes/novo',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/compras/': RouteRecordInfo<
      '/compras/',
      '/compras',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/compras/[id]': RouteRecordInfo<
      '/compras/[id]',
      '/compras/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/configuracoes/permissoes': RouteRecordInfo<
      '/configuracoes/permissoes',
      '/configuracoes/permissoes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/configuracoes/usuarios': RouteRecordInfo<
      '/configuracoes/usuarios',
      '/configuracoes/usuarios',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/constantes/': RouteRecordInfo<
      '/constantes/',
      '/constantes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/constantes/[id]': RouteRecordInfo<
      '/constantes/[id]',
      '/constantes/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/despesas/': RouteRecordInfo<
      '/despesas/',
      '/despesas',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/despesas/[id]': RouteRecordInfo<
      '/despesas/[id]',
      '/despesas/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/financeiro/contas-pagar/': RouteRecordInfo<
      '/financeiro/contas-pagar/',
      '/financeiro/contas-pagar',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/financeiro/contas-receber/': RouteRecordInfo<
      '/financeiro/contas-receber/',
      '/financeiro/contas-receber',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/fornecedores/': RouteRecordInfo<
      '/fornecedores/',
      '/fornecedores',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/fornecedores/[id]': RouteRecordInfo<
      '/fornecedores/[id]',
      '/fornecedores/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/fornecedores/novo': RouteRecordInfo<
      '/fornecedores/novo',
      '/fornecedores/novo',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/funcionarios/': RouteRecordInfo<
      '/funcionarios/',
      '/funcionarios',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/funcionarios/[id]': RouteRecordInfo<
      '/funcionarios/[id]',
      '/funcionarios/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/orcamentos/': RouteRecordInfo<
      '/orcamentos/',
      '/orcamentos',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/orcamentos/[id]': RouteRecordInfo<
      '/orcamentos/[id]',
      '/orcamentos/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/orcamentos/novo': RouteRecordInfo<
      '/orcamentos/novo',
      '/orcamentos/novo',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/plano-corte/': RouteRecordInfo<
      '/plano-corte/',
      '/plano-corte',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/plano-corte/[id]': RouteRecordInfo<
      '/plano-corte/[id]',
      '/plano-corte/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/plano-corte/novo': RouteRecordInfo<
      '/plano-corte/novo',
      '/plano-corte/novo',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/producao/agenda': RouteRecordInfo<
      '/producao/agenda',
      '/producao/agenda',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/produtos/': RouteRecordInfo<
      '/produtos/',
      '/produtos',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/produtos/[id]': RouteRecordInfo<
      '/produtos/[id]',
      '/produtos/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/vendas/': RouteRecordInfo<
      '/vendas/',
      '/vendas',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/vendas/[id]': RouteRecordInfo<
      '/vendas/[id]',
      '/vendas/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/vendas/novo': RouteRecordInfo<
      '/vendas/novo',
      '/vendas/novo',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/clientes/index.vue': {
      routes:
        | '/clientes/'
      views:
        | never
    }
    'src/pages/clientes/[id].vue': {
      routes:
        | '/clientes/[id]'
      views:
        | never
    }
    'src/pages/clientes/novo.vue': {
      routes:
        | '/clientes/novo'
      views:
        | never
    }
    'src/pages/compras/index.vue': {
      routes:
        | '/compras/'
      views:
        | never
    }
    'src/pages/compras/[id].vue': {
      routes:
        | '/compras/[id]'
      views:
        | never
    }
    'src/pages/configuracoes/permissoes.vue': {
      routes:
        | '/configuracoes/permissoes'
      views:
        | never
    }
    'src/pages/configuracoes/usuarios.vue': {
      routes:
        | '/configuracoes/usuarios'
      views:
        | never
    }
    'src/pages/constantes/index.vue': {
      routes:
        | '/constantes/'
      views:
        | never
    }
    'src/pages/constantes/[id].vue': {
      routes:
        | '/constantes/[id]'
      views:
        | never
    }
    'src/pages/despesas/index.vue': {
      routes:
        | '/despesas/'
      views:
        | never
    }
    'src/pages/despesas/[id].vue': {
      routes:
        | '/despesas/[id]'
      views:
        | never
    }
    'src/pages/financeiro/contas-pagar/index.vue': {
      routes:
        | '/financeiro/contas-pagar/'
      views:
        | never
    }
    'src/pages/financeiro/contas-receber/index.vue': {
      routes:
        | '/financeiro/contas-receber/'
      views:
        | never
    }
    'src/pages/fornecedores/index.vue': {
      routes:
        | '/fornecedores/'
      views:
        | never
    }
    'src/pages/fornecedores/[id].vue': {
      routes:
        | '/fornecedores/[id]'
      views:
        | never
    }
    'src/pages/fornecedores/novo.vue': {
      routes:
        | '/fornecedores/novo'
      views:
        | never
    }
    'src/pages/funcionarios/index.vue': {
      routes:
        | '/funcionarios/'
      views:
        | never
    }
    'src/pages/funcionarios/[id].vue': {
      routes:
        | '/funcionarios/[id]'
      views:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
    }
    'src/pages/orcamentos/index.vue': {
      routes:
        | '/orcamentos/'
      views:
        | never
    }
    'src/pages/orcamentos/[id].vue': {
      routes:
        | '/orcamentos/[id]'
      views:
        | never
    }
    'src/pages/orcamentos/novo.vue': {
      routes:
        | '/orcamentos/novo'
      views:
        | never
    }
    'src/pages/plano-corte/index.vue': {
      routes:
        | '/plano-corte/'
      views:
        | never
    }
    'src/pages/plano-corte/[id].vue': {
      routes:
        | '/plano-corte/[id]'
      views:
        | never
    }
    'src/pages/plano-corte/novo.vue': {
      routes:
        | '/plano-corte/novo'
      views:
        | never
    }
    'src/pages/producao/agenda.vue': {
      routes:
        | '/producao/agenda'
      views:
        | never
    }
    'src/pages/produtos/index.vue': {
      routes:
        | '/produtos/'
      views:
        | never
    }
    'src/pages/produtos/[id].vue': {
      routes:
        | '/produtos/[id]'
      views:
        | never
    }
    'src/pages/vendas/index.vue': {
      routes:
        | '/vendas/'
      views:
        | never
    }
    'src/pages/vendas/[id].vue': {
      routes:
        | '/vendas/[id]'
      views:
        | never
    }
    'src/pages/vendas/novo.vue': {
      routes:
        | '/vendas/novo'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
