/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/clientes/': RouteRecordInfo<
      '/clientes/',
      '/clientes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/clientes/[id]': RouteRecordInfo<
      '/clientes/[id]',
      '/clientes/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/clientes/novo': RouteRecordInfo<
      '/clientes/novo',
      '/clientes/novo',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/configuracoes/usuarios/': RouteRecordInfo<
      '/configuracoes/usuarios/',
      '/configuracoes/usuarios',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/constantes/': RouteRecordInfo<
      '/constantes/',
      '/constantes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/constantes/[id]': RouteRecordInfo<
      '/constantes/[id]',
      '/constantes/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/constantes/novo': RouteRecordInfo<
      '/constantes/novo',
      '/constantes/novo',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/despesas/': RouteRecordInfo<
      '/despesas/',
      '/despesas',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/despesas/[id]': RouteRecordInfo<
      '/despesas/[id]',
      '/despesas/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/despesas/novo': RouteRecordInfo<
      '/despesas/novo',
      '/despesas/novo',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/fornecedores/': RouteRecordInfo<
      '/fornecedores/',
      '/fornecedores',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/fornecedores/[id]': RouteRecordInfo<
      '/fornecedores/[id]',
      '/fornecedores/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/fornecedores/novo': RouteRecordInfo<
      '/fornecedores/novo',
      '/fornecedores/novo',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/funcionarios/': RouteRecordInfo<
      '/funcionarios/',
      '/funcionarios',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/funcionarios/[id]': RouteRecordInfo<
      '/funcionarios/[id]',
      '/funcionarios/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/funcionarios/novo': RouteRecordInfo<
      '/funcionarios/novo',
      '/funcionarios/novo',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/plano-corte/': RouteRecordInfo<
      '/plano-corte/',
      '/plano-corte',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/plano-corte/[id]': RouteRecordInfo<
      '/plano-corte/[id]',
      '/plano-corte/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/plano-corte/novo': RouteRecordInfo<
      '/plano-corte/novo',
      '/plano-corte/novo',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/produtos/': RouteRecordInfo<
      '/produtos/',
      '/produtos',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/produtos/[id]': RouteRecordInfo<
      '/produtos/[id]',
      '/produtos/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/produtos/novo': RouteRecordInfo<
      '/produtos/novo',
      '/produtos/novo',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/clientes/index.vue': {
      routes:
        | '/clientes/'
      views:
        | never
    }
    'src/pages/clientes/[id].vue': {
      routes:
        | '/clientes/[id]'
      views:
        | never
    }
    'src/pages/clientes/novo.vue': {
      routes:
        | '/clientes/novo'
      views:
        | never
    }
    'src/pages/configuracoes/usuarios/index.vue': {
      routes:
        | '/configuracoes/usuarios/'
      views:
        | never
    }
    'src/pages/constantes/index.vue': {
      routes:
        | '/constantes/'
      views:
        | never
    }
    'src/pages/constantes/[id].vue': {
      routes:
        | '/constantes/[id]'
      views:
        | never
    }
    'src/pages/constantes/novo.vue': {
      routes:
        | '/constantes/novo'
      views:
        | never
    }
    'src/pages/despesas/index.vue': {
      routes:
        | '/despesas/'
      views:
        | never
    }
    'src/pages/despesas/[id].vue': {
      routes:
        | '/despesas/[id]'
      views:
        | never
    }
    'src/pages/despesas/novo.vue': {
      routes:
        | '/despesas/novo'
      views:
        | never
    }
    'src/pages/fornecedores/index.vue': {
      routes:
        | '/fornecedores/'
      views:
        | never
    }
    'src/pages/fornecedores/[id].vue': {
      routes:
        | '/fornecedores/[id]'
      views:
        | never
    }
    'src/pages/fornecedores/novo.vue': {
      routes:
        | '/fornecedores/novo'
      views:
        | never
    }
    'src/pages/funcionarios/index.vue': {
      routes:
        | '/funcionarios/'
      views:
        | never
    }
    'src/pages/funcionarios/[id].vue': {
      routes:
        | '/funcionarios/[id]'
      views:
        | never
    }
    'src/pages/funcionarios/novo.vue': {
      routes:
        | '/funcionarios/novo'
      views:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
    }
    'src/pages/plano-corte/index.vue': {
      routes:
        | '/plano-corte/'
      views:
        | never
    }
    'src/pages/plano-corte/[id].vue': {
      routes:
        | '/plano-corte/[id]'
      views:
        | never
    }
    'src/pages/plano-corte/novo.vue': {
      routes:
        | '/plano-corte/novo'
      views:
        | never
    }
    'src/pages/produtos/index.vue': {
      routes:
        | '/produtos/'
      views:
        | never
    }
    'src/pages/produtos/[id].vue': {
      routes:
        | '/produtos/[id]'
      views:
        | never
    }
    'src/pages/produtos/novo.vue': {
      routes:
        | '/produtos/novo'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
